// Generated by setup.html on 2026-09-13T15:37:32.698Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://wzqrunyvcfmxbpcobbvd.supabase.co";
window.SUPABASE_KEY = "sb_publishable_PakRgAD2sGbbFEfU9FnQTg_Os6XQkbB";
